### PR TITLE
fix .app method (store update 2020-06-16)

### PR DESCRIPTION
**Pull request by icarcal**
This PR fixes the following issues:
#407 

I have updated the following methods:
`.app`

Google Play store changed the way that the script `AF_initDataCallback` is handled.
I have updated the regex to match the new script.

I've also updated the tests and docs, refactored the mapping for app details, and included a new field `maxInstalls`

### CODE REVIEW

**Comment by berrybar** [comment]
I applied this code, but encountered a new error.

Tue Jun 16 2020 13:58:27 GMT+0900 (GMT+09:00) Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1 an error occuerd!
D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors

Error: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\workspace\googleplayscraper\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\workspace\googleplayscraper\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    --------------------
    at Protocol._enqueue (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at PoolConnection.query (D:\workspace\googleplayscraper\node_modules\mysql\lib\Connection.js:201:25)
    at D:\workspace\googleplayscraper\main.js:12:17
    at Handshake.onConnect (D:\workspace\googleplayscraper\node_modules\mysql\lib\Pool.js:64:7)
    at Handshake.<anonymous> (D:\workspace\googleplayscraper\node_modules\mysql\lib\Connection.js:525:10)
    at Handshake._callback (D:\workspace\googleplayscraper\node_modules\mysql\lib\Connection.js:491:16)
    at Handshake.Sequence.end (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Handshake.Sequence.OkPacket (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\sequences\Sequence.js:92:8)
    at Protocol._parsePacket (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\workspace\googleplayscraper\node_modules\mysql\lib\protocol\Parser.js:433:10)

Which column value should I change?

**Comment by jayesh83** [comment]
@icarcal When it will be merged man? 😪

**Comment by jayesh83** [comment]
Till then I think I'll have to to use your repo I guess ! Thanks btw

**Comment by Djip** [comment]
Works like a charm.. implemented it into my own fork already. Thanks a lot

**Comment by berrybar** [comment]
This works for me. Thanks!

**Comment by usman10scorpio** [comment]
The maxInstalls count does not match with actual installs when I see them in my play console (android app )

Screenshot_2020-06-23-16-38-26-876_com google android apps playconsole22


image

**Comment by icarcal** [comment]
@usman10scorpio 
This is a number that google play allow us to fetch.
It is not accurate, but it is close to what google play allow us to "see".

For a better understanding, check [here](https://github.com/facundoolano/google-play-scraper/issues/415#issuecomment-648175845) and [here](https://github.com/facundoolano/google-play-scraper/issues/413#issuecomment-648174014) for a more detailed explanation.

**Pull request merged**
