### PR TITLE
set optional memoization

### PR DESCRIPTION
**Pull request by icaroponce**
Since this feature was already discussed and implemented on `app-store-scraper` module, and have seen that there're still some opened issues here related to it, I decided to port it from the `app-store-scraper` module to this one, making both of them compatible in the memoization API.

It should fix the #137 and #142 issues as well.

### CODE REVIEW

**Comment by facundoolano** [comment]
The problem with this is that in this case the utils/parseList.js file is using internally the app.js code (for the fullDetail calls), and memoizing options in this PR are not applied to that internal call. It's very important to me to be able to memoize those calls, since they were the motivation of memoization in the first place: fullDetail calls are the most expensive calls (as seen in the aso module).

Also, this seems to make the tests fail.

**Comment by icaroponce** [comment]
I'll test it again, idk why the tests failded, I had tested it sometimes before submit the pr.
Is it possible to know which test failed on Travis?

Since we are memoizing each method, I think that the app method called by parseList is memoized as well, so it'd cache each call of parseList too.

Let me check it once more and I'll let you know.

**Comment by icaroponce** [comment]
@facundoolano , I've tested it a ton of times again. 
Some tests failed due to timeout at times, and other times tests didn't failed. 
(I know it's strange. but as it depends on my network connection and on goople play response time), 
Some test could take more than 5s to run on Travis.  

Maybe can we check if there was some timeout error when running the tests on travis?

About the `fullDetail: true` usage, if I got your point right, it's working as expected. 

Running the code above: 

```js
const gplay = require('../google-play-scraper').memoized();

gplay.list({
  category: gplay.category.GAME_ACTION,
  collection: gplay.collection.TOP_FREE,
  num: 1,
  fullDetail: true
})
  .then(items => items.map(item => item.offersIAP))
  .then(console.log);

gplay.list({
  category: gplay.category.GAME_ACTION,
  collection: gplay.collection.TOP_FREE,
  num: 1,
  fullDetail: true
});
```
I'm getting the following response:
```
DEBUG=google-play-scraper node gplay.js
  google-play-scraper Making request: {"url":"https://play.google.com/store/apps/category/GAME_ACTION/collection/topselling_free?hl=en&gl=us&num=1","method":"POST","form":{"start":0}} +0ms
  google-play-scraper Request finished +389ms
  google-play-scraper Making request: {"url":"https://play.google.com/store/apps/details?id=com.fortafygames.colorswitch&hl=en&gl=us"} +76ms
  google-play-scraper Request finished +423ms
[ true ]
[ true ]
```
As you can see, it didn't request the details or list again, it did only 2 requests, one for get the list, and the another one to get the apps detail, and, the next method call didn't make any requests, it did hit the cache.

**Comment by facundoolano** [comment]
Yes, that example works, but I'm interested in other, subtler cases. Say you do: 

```js
gplay.search({term: "panda", fullDetail: true})
gplay.search({term: "panda game", fullDetail: true})
```

Both searches are likely to share most of the results, and thus the inner app detail calls will be the same, but since the `search` calls differ, no memoization will happen. The current implementation does cover this case. I've found many cases like this one while developing the aso module (not to say this scraper should accommodate to the other module's needs, but since we're supporting memoization, I prefer to take full advantage of it).

This would require to have some sort of initialization of the app function (or maybe the parseList one) and passing it around to the files that make use of it. I haven't thought it much myself yet, to be honest.

**Comment by icaroponce** [comment]
Got your point, you're absolutely right. I haven't thought in this subtler case, and it'd be quite useful. 

I'll take a deeper look trough code and try to accomplish it. 

Feel free to close this PR in the meanwhile if you want.

**Comment by icaroponce** [comment]
Hi, 

I took a deeper look through the code and couldn't find a reasonable solution for sharing the memoized modules internally, unfortunately. 

If anyone reading this pr have something in mind, please spread the word. 

I also wanna ask to @facundoolano what you think about merge this memoization setup  as it is, considering that we still have some opened issues and it is affecting directly the simple user trying to use and getting started to this module. And regarding to the compatibility to `aso` module, we don't need necessarily to update this module version there right now, we could do it as soon as we find a way to share the memoization internally.

**Comment by facundoolano** [comment]
Closing this as a memoization refactor is already published.

**Pull request closed without merging**
