### PR TITLE
fix .list method (store update 2019-09-01)

### PR DESCRIPTION
**Pull request by icarcal**
This PR fixes the following issues:
#333
#334
#336

I have updated the following methods:
```.list```

.list method introduce some breaking changes, since google allow you to fetch data only through ```batchexecute``` endpoint.
You can now only send the ```num``` parameter (it will allow you to fetch the desired number of category apps).
The ```.list``` method is unstable right now, since google sometimes respond with 200 apps, and sometimes more (for example 600 and so on).

Check #333 for more info about this

I've also updated the tests and docs

### CODE REVIEW

**Comment by vitaliy901** [comment]
I have one issue, gp.list({collection: 'topselling_free', num: 100}).then(res => {
    console.log(res);
})

Gives me Error: 
 TypeError: Cannot read property 'topselling_free' of undefined

**Comment by icarcal** [comment]
@vitaliy901 thanks!
Gonna to look into it!

**Comment by icarcal** [comment]
@vitaliy901 fixed ```.list``` for top collections.
Can you check if this is working correctly right now?

**Comment by vitaliy901** [comment]
@irarcal still same - gp.list({collection: gp.collection.TRENDING, num: 100}).then(res => {
    console.log(res);
})

TypeError: Cannot read property 'movers_shakers' of undefined

i see that it doesn't work, when there is no opts.category ...

**Comment by vitaliy901** [comment]
@icarcal

**Comment by vitaliy901** [comment]
@icarcal parameter start, now doen't work too ?

**Comment by icarcal** [comment]
@vitaliy901 no.
This is a breaking change,
You can now only send the `num` parameter (it will allow you to fetch the desired number of category apps).

You can check a little bit more about this discussion at #337

**Comment by vitaliy901** [comment]
@icarcal i think for working test and another api package "google-play-api", start option should work

**Pull request merged**
