### PR TITLE
Unit tests, grunt, validate and refactoring.

### PR DESCRIPTION
**Pull request by danbit**
Unit tests, validate, grunt and refactoring.

### CODE REVIEW

**Comment by facundoolano** [comment]
Still conflicting, sorry. You need to pull the latest dev code and solve any conflicts your branch has with the new code.

**Comment by danbit** [comment]
@facundoolano its done.

**Comment by facundoolano** [comment]
I'm not sure we should introduce the grunt dependency just for a couple of tests, using plain mocha sounds better. 

Also these are a lot of changes to review, specially while we don't have tests. It would be better if you send smaller chunks at a time.

**Comment by danbit** [comment]
The grunt work not only for testing, added the grunt-complexity plugin to help improve the quality of code and plugins grunt-contrib-watch ',' grunt-contrib-jshint 'and' grunt-jsbeautifier '.
The big change was inevitable because of refactoring. You can cancel this pull request, I will add more test cases and sent another.

**Pull request closed without merging**
