### PR TITLE
Add SDK API level

### PR DESCRIPTION
**Pull request by tgalopin**
Add a field for the SDK API level.

See https://source.android.com/source/build-numbers.html

### CODE REVIEW

**Comment by facundoolano** [comment]
I'm not that familiar with android dev, what's the use of the SDK API level?

**Comment by tgalopin** [comment]
The api level is used for compatibility : as an android developer,  you use it to declare what version you support and therefore which sdk features you are using.

**Comment by facundoolano** [comment]
This feels somewhat unrelated to the Google Play scraper. The change adds a bit of clutter to the code and implies maintaining that mapping of version to api level. It sounds more sensible to keep that mapping in the clients of the library. 

I'm interested in knowing if anyone else would benefit from this, though, so I'm going to leave this PR open for a while.

**Comment by tgalopin** [comment]
It seems fair :) . I'll put it in my code then.

**Comment by facundoolano** [comment]
Nobody chimed in asking for this, so I'm closing it for now.

**Pull request closed without merging**
