### PR TITLE
Use new regex for getting clp

### PR DESCRIPTION
**Pull request by laoshanlung**

### CODE REVIEW

**Comment by laoshanlung** [comment]
Will revert back to the original version once this PR (https://github.com/facundoolano/google-play-scraper/pull/140) is merged

**Comment by laoshanlung** [comment]
I guess Google Play has recently changed something in their HTML code which breaks the old regular expression

**Comment by facundoolano** [comment]
Can you elaborate on what has broken that this PR fix?

**Comment by laoshanlung** [comment]
When I tried searching for a game (for example `Clash of Clans`), the following (new?) HTML code doesn't work with the old regex (in the sense that it results in wrong matches)

```
track-impression tight square-cover apps" data-uitype="400"> <div class="cluster-heading">  <h2 class="single-title-link"> <a class="title-link id-track-click" data-server-cookie="CAMiKQgBEAMaIxIhChtzZWFyY2hfcmVzdWx0c19jbHVzdGVyX2FwcHMQLRgD" data-uitype="291" href="/store/apps/collection/search_results_cluster_apps?clp=ggEQCg5jbGFzaCBvZiBjbGFucw%3D%3D:S:ANO1ljIpR-0">Apps</a> <span>  <a class="see-more play-button small id-track-click apps id-responsive-see-more" data-always-show="true" data-server-cookie="CAMiKQgBEAMaIxIhChtzZWFyY2hfcmVzdWx0c19jbHVzdGVyX2FwcHMQLRgD" data-uitype="290" href="/store/apps/collection/search_results_cluster_apps?clp=ggEQCg5jbGFzaCBvZiBjbGFucw%3D%3D:S:ANO1ljIpR-0" aria-label=" Check out more content from Apps "> See more </a>   </span> </h2>
```

also, the test in `dev` failed

**Comment by facundoolano** [comment]
Just tested and could reproduce the issue, your commit fixes it. Thanks!

**Comment by laoshanlung** [comment]
Can you bump the version? Because this basically affects all the currently running code

**Comment by facundoolano** [comment]
already did

**Pull request merged**
