### PR TITLE
Master

### PR DESCRIPTION
**Pull request by danbit**
Hi, I am using this lib for my Android application and needed to get the details of the error. Before starting the development of this new feature I decided to add test unit so that my changes did not break what already works today.It remains to implement other tests, only created the basics. The refactoring the code was made to correct errors and alerts found by Jshint and Complexity of Grunt.

### CODE REVIEW

**Comment by facundoolano** [comment]
Great, tests are welcome! 

This has conflicts, though. Also make the pull to the dev branch, not master. Closing, you can open a new one to dev.

**Comment by danbit** [comment]
Hi, sorry is my first pull request :). 	
Do not get it right, it did a pull request of my master for your dev, is to make dev to dev?

**"danbit  wants to merge 10 commits into facundoolano:dev from danbit:master"**

**Comment by facundoolano** [comment]
First you need to update your working branch to develop, and do all the stuff there. Master is only to put the latest code whenever I make a release.

**Comment by danbit** [comment]
Ok.I developed it in dev, but I made a merge with the master later. I'll send another dev to dev.

**Pull request closed without merging**
