### PR TITLE
add appId to permissioins response

### PR DESCRIPTION
**Pull request by taisuke-ohmi**
When executing the permissions method consecutively for multiple appid, I didn't know the result for which appid.
So I added appId to the permissions method.

### CODE REVIEW

**Comment by taisuke-ohmi** [comment]
I rebase when https://github.com/facundoolano/google-play-scraper/pull/266 is merged. Then the test should pass.

**Comment by facundoolano** [comment]
I don't get the need for this, you can extend the result with the app id without having to modify this method.

**Comment by facundoolano** [comment]
```js
 gplay.permissions({appId: appId})
         .then((permissions) => ({permissions, appId}))
```

**Comment by taisuke-ohmi** [comment]
I see, thanks.

**Pull request closed without merging**
