### PR TITLE
Default language fix

### PR DESCRIPTION
**Pull request by arkty**
Google play can return all reviews if hl option not set. No need to have default 'en' lang.

### CODE REVIEW

**Comment by facundoolano** [comment]
This behavior is intentional, we want to have the same default language regardless of the place where the library is being run (otherwise different users will get different results running the same code).

**Comment by facundoolano** [comment]
Not sure what that option would mean. We need to use something supported by the google play website.

**Comment by arkty** [comment]
@facundoolano Google play supports requests without **hl** option. In this case, you can get all reviews in all languages.

I want to add option **all** into opts.lang (or remove default **en**, but it was rejected). 

There will be 3 cases:
1. opts.lang not set - default **en** language, as now.
2. opts.lang set to **all** - do not include **hl** into request (my case) and get all reviews.
3. opts.lang set to other value - use opts.lang in request, as now.

**Comment by facundoolano** [comment]
Oh ok, I didn't realize that reviews behaved differently than the other pages

**Comment by arkty** [comment]
@facundoolano so, should I add an **all** option or remove **default** hl when no lang specified (as now in PR)?

**Comment by facundoolano** [comment]
`all` makes sense as an extra option. Make sure to mention it in the README.

**Comment by yurganov** [comment]
@arkty, @facundoolano  you should be more careful with such behavior - not to set hl param at all. 

>>In this case, you can get all reviews in all languages.
If it so for now (and I am not sure), it can switch in any time to geo-based detection of IP.

**Comment by arkty** [comment]
@yurganov hi! Thank you for research. 
I will try to reproduce it. Last time i got this result: different reviews when using 'ru' and w/0 hl. So, if it's now geo based, this should return same results.
I will double check it.

**Comment by yurganov** [comment]
@arkty yes, i think different reviews between hl=ru and w/o hl is because of your IP.

And do not forget, that Google theoretically can think that your IP from another country.

**Comment by facundoolano** [comment]
Closing as it looks like we can't rely on the default response sent by google.

**Pull request closed without merging**
