### PR TITLE
fix 'Invalid Date' on reviews response

### PR DESCRIPTION
**Pull request by icarcal**
This PR fixes the following issues:
#348 

I have updated the following methods:
`.reviews`

The date array for reviews dates sometimes have only one position, so I have added `000` as default when the second position is not found.

### CODE REVIEW

**Comment by marxsk** [comment]
@icarcal Wouldn't it better to just return undefined? This can introduce new types of errors as people expect that the date is correct. So, they won't detect this immediately.

**Comment by facundoolano** [comment]
Will this return a valid date in all cases?

**Comment by facundoolano** [comment]
Also, does the example in README reflect the format the dates are being returned in?

**Comment by icarcal** [comment]
@facundoolano 
> Will this return a valid date in all cases?

I checked for the example on #348 example and I have the following cases for the date array:
```
[ 1563785933, 50000000 ]
[ 1561903055, 117000000 ]
[ 1558104094, 799000000 ]
[ 1557645130, 99000000 ]
[ 1555736420, 61000000 ]
[ 1554881170 ]
```

So I put together the first part plus the first 3 digits of the second one, which gives me a valid date (it is the same as the store).
The last date do not have the second part, so I add the `000`, for the same reason.
In fact, if you add `000` for all dates, it gives you pretty much the same result, for example:
```
new Date(1563785933000)
// Mon Jul 22 2019 05:58:53 GMT-0300 (Brasilia Standard Time)
new Date(1563785933500)
// Mon Jul 22 2019 05:58:53 GMT-0300 (Brasilia Standard Time)
```

I made some tests and this last part of the timestamp is the milliseconds.
The date will not be changed at all.

I checked for other results, but couldn't find, so I think this covers all cases.

> Also, does the example in README reflect the format the dates are being returned in?

I have updated the README now.
I can change the return to be the given date (`2019-07-22T08:58:53.000Z`) instead the string, what do you think about it?

**Comment by facundoolano** [comment]
@icarcal yes, a Date object would be better if possible

**Pull request merged**
