### PR TITLE
Added country parameter in app method

### PR DESCRIPTION
**Pull request by pingyen**
If the app is not published in US, we cannot fetch the app data by current app method, so I added parameter country in app method.

### CODE REVIEW

**Comment by gurdotan** [comment]
+1

**Comment by facundoolano** [comment]
Can you provide a couple of URLs showing the difference of specifying the country? When I first coded this the gl parameter seemed to be ignored in the app detail.

**Comment by pingyen** [comment]
Hi @facundoolano,

Sorry for late response.

You will get 404 in following URL:

https://play.google.com/store/apps/details?id=air.com.igroslot.columbusSlotsAndroid&gl=us

You can get a Russian page in following URL:

https://play.google.com/store/apps/details?id=air.com.igroslot.columbusSlotsAndroid&gl=ru

Currently, I do not have many samples, but if the app is not published in US, we need parameter country.

Thanks,
Ping-Yen

**Comment by facundoolano** [comment]
I don't have a computer available to test this currently, I'll review as soon as I can

**Comment by gurdotan** [comment]
@pingyen I took the liberty of testing this quickly with the above URLs but it seems that the URLs above don't work without this PR as well

**Comment by pingyen** [comment]
Hi @gurdotan,

I do not get the point.

What do you mean "the URLs above don't work without this PR as well"?

If you use an Israel IP, the following URL should be OK:

https://play.google.com/store/apps/details?id=air.com.igroslot.columbusSlotsAndroid

Because app air.com.igroslot.columbusSlotsAndroid is published in Israel.

But if you use a US IP, the above URL will not work, because app air.com.igroslot.columbusSlotsAndroid is not published in US.

That is why we need this PR.

If we have this PR, we can access an Israel app by a US IP.

**Comment by gurdotan** [comment]
@pingyen aah got your point, thanks.

**Comment by facundoolano** [comment]
Ok @pingyen I finally got the chance to test your links above and see why this is needed. Now, before I merge this I think it makes more sense to use an opts object as in the rest of the methods of the scraper, since the parameters are now three. Also this new parameter will need documentation in the README. 

You can do that in this PR if you want otherwise I'll end up doing it myself in the next couple of days.

**Comment by facundoolano** [comment]
This is solved in 9cc94f52fd891f2e7bd2760c1804a3e39f79b215

**Pull request closed without merging**
