### PR TITLE
fix redirect to reCaptcha if response status is 302

### PR DESCRIPTION
**Pull request by yura415**
Fix for #182

### CODE REVIEW

**Comment by facundoolano** [comment]
Thanks! Is there a test that fails for this? If not can you show an example code that would fail without this (or, if you have the time, a test that fails without your fix)?

**Comment by yura415** [comment]
It doesn't breaks anything. Without this setting for example `list` request from IP that is banned on Play Store will resolve with empty array instead of throwing an error. The issue here is that actual code of the page will be 302 Moved redirect to ReCaptcha instead of 503 with that same ReCaptcha. So we need to follow that redirect in order to get correct error code from the page.

There is no test covering this. And maybe the only test case is to ban your IP by sending many requests to Play Store.

**Comment by facundoolano** [comment]
Oh ok, got it now.

**Comment by facundoolano** [comment]
Can you remove the package-lock?

**Comment by facundoolano** [comment]
Thanks. I like the fact that you've added a requestOptions, in case the user needs to override some configuration. Can you remove the `proxy` options, though? since it's the kind of thing that should be handled through `requestOptions` from now on.

**Comment by yura415** [comment]
Ok. I'll remove it.

**Comment by yura415** [comment]
I've removed proxy option and also added requestOptions in developer & search initial requests.

Submitted PR for app-store-scraper with similar functionality: https://github.com/facundoolano/app-store-scraper/pull/44

**Comment by facundoolano** [comment]
Thanks!

**Pull request merged**
