### PR TITLE
Fixed failed test case

### PR DESCRIPTION
**Pull request by taisuke-ohmi**
The app of "com.dxco.pandavszombies" has been deleted. Also, because there was an item that did not have a value, I fixed it.

### CODE REVIEW

**Comment by facundoolano** [comment]
I see that you removed several checks, are those because of bugs in the mapings? Are those resolved in another PR?

**Comment by facundoolano** [comment]
I don't like assertions commented, if the mappings changed, the tests are supposed to fail.

**Comment by taisuke-ohmi** [comment]
Please try the app method once.
For example)
gplay.app({appId: 'jp.naver.line.android'})
  .then(console.log, console.log);
You will find that some items are "undefined". If you do not change the test you will need to fix bugs in mapping.

**Comment by facundoolano** [comment]
That's ok, I rather have failing tests denoting something's broken. Please update the PR so no assertions are commented out.

**Comment by taisuke-ohmi** [comment]
Since mapping was fixed, I rebased and returned the part commented out.
Also, since comments has not been acquired yet, I fixed it. Please also check https://github.com/facundoolano/google-play-scraper/pull/267

**Comment by facundoolano** [comment]
cool, thanks!

**Pull request merged**
