### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by KKitar**
Update to retrieve Apps description.

### CODE REVIEW

**Comment by facundoolano** [comment]
Why is this needed? description was already present, and with this change it doesn't look like descriptionHTML would keep working

**Comment by KKitar** [comment]
Well, I tried to use your code to retrieve description but it doesn't work so I had  to make some changes and now it works perfectly.

**Comment by facundoolano** [comment]
I did a test today with the current dev code and it worked. Can you show me the code that wasn't working for you?

**Comment by facundoolano** [comment]
I was able to reproduce this now, and pushed a fix. Thanks!

**Pull request closed without merging**
