### PR TITLE
Replace querystring with URLSearchParams

### PR DESCRIPTION
**Pull request by pavi2410**

### CODE REVIEW

**Comment by facundoolano** [comment]
any particular reason for this change?

**Comment by pavi2410** [comment]
Deno / Cloudflare Workers support. Because `querystring` module doesn't exist outside Node.

**Comment by facundoolano** [comment]
hrm I think if that's the case the right thing to do here would be to add a github check that this runs on deno, otherwise it could break again with further changes

**Comment by pavi2410** [comment]
It won't break as it uses an standard web API and I tested this when working on https://github.com/pavi2410/PlayBadges

However, Deno or better, standard web API compatibility would be awesome.

**Comment by facundoolano** [comment]
Closing this as it doesn't make sense to make an isolated change for deno support without adding the rest of the infra to support it.

**Pull request closed without merging**
