### PR TITLE
update Mapping role to respond google play revision

### PR DESCRIPTION
**Pull request by yangyangFE**
The google play today's revision caused some errors, I fixed some, but the following fields I don't know the meaning,  they are 'currency', 'familyGenre', 'familyGenreId' and 'contentRatingDescription',  Hope someone can fix it earlier.

### CODE REVIEW

**Comment by lomik** [comment]
Replacement `ds:10` to `ds:11` is wrong. `ds:10` should be changed to `ds:3`

**Comment by yurganov** [comment]
@yangyangFE, you did it great. Please, change ds:10 to ds:3 and re-run tests.

**Comment by yurganov** [comment]
family* fields are only contains in apps from FAMILY category

f.e.
com.foxandsheep.nightynight3

And it works with your mappings.

**Comment by yurganov** [comment]
Don't worry. I'll look up into test now.

**Comment by yershalom** [comment]
@yurganov Let me know if you need another pair of eyes...

**Comment by yurganov** [comment]
@yershalom @yangyangFE it seems, that field comments is not filled properly.

**Comment by yurganov** [comment]
@yangyangFE please, change mapping of comments from ds:22 to ds:15

You should check mappings in curl request, not in the browser's source code.

**Comment by yangyangFE** [comment]
> @yangyangFE please, change mapping of comments from ds:22 to ds:15
> 
> You should check mappings in curl request, not in the browser's source code.

sorry, I did't find  ds:22. Do you know the meaning of comments？ Thank you very much.

**Comment by yangyangFE** [comment]
> @yangyangFE please, change mapping of comments from ds:22 to ds:15
> 
> You should check mappings in curl request, not in the browser's source code.

**Comment by yangyangFE** [comment]
@yurganov Sorry, I did't find ds:22. Do you know the meaning of comments？ Thank you very much.

**Comment by yershalom** [comment]
@yangyangFE change the comment to be like this:
```
comments: {
    path: ['ds:15', 0],
    fun: extractComments
  }
```

**Comment by yurganov** [comment]
@yangyangFE you did it great.

@facundoolano, we need your reaction to this PR.

**Comment by facundoolano** [comment]
@yurganov app tests passing and it looks like you only modified mappings, so I'm merging it.

Thanks for handling this.

**Comment by facundoolano** [comment]
To everyone else, please make sure to file an issue if you find some other field that broke in the process.

**Pull request merged**
