### PR TITLE
update: mapping tmp

### PR DESCRIPTION
**Pull request by huoyinghui**
tmp update mapping

### CODE REVIEW

**Comment by huoyinghui** [comment]
@facundoolano ， Mapping is currently valid， There are potential future updates that can delay consolidation

**Comment by facundoolano** [comment]
Thanks @huoyinghui, this seems to fix the issues, but there's still one failing test, can you fix it?

**Comment by huoyinghui** [comment]
@facundoolano , test ok

**Comment by facundoolano** [comment]
Thanks!

**Comment by filoozom** [comment]
Hi, can we get a new release for this? Thanks!

**Comment by facundoolano** [comment]
Published 6.0.4

**Pull request merged**
