### PR TITLE
Add developer physical address

### PR DESCRIPTION
**Pull request by koAlech**
Added parsing the developer's physical address in case it exists

### CODE REVIEW

**Comment by facundoolano** [comment]
Thanks, can you add it to the README examples too?

**Comment by koAlech** [comment]
I guess the only place that requires documentation is the results example for the app call. The problem is that the current example `com.dxco.pandavszombies` does not have a physical address therefore `developerAddress` is omitted in the response. 
What do you suggest to do? Add a different example with an address defined?

**Comment by facundoolano** [comment]
Nah just use the address of a different developer in that same example.

**Comment by koAlech** [comment]
Done

**Comment by facundoolano** [comment]
Thanks!

**Comment by koAlech** [comment]
😎

**Pull request merged**
