### PR TITLE
fix mappings (store update 2022-01-06)

### PR DESCRIPTION
**Pull request by icarcal**
This PR fixes the following issues:
#497
#496 

The mappings were incorrect after the store update

I have also:
[b1043c1](https://github.com/facundoolano/google-play-scraper/commit/b1043c15e2b7874952a894b10028d66dc6155e4a): fixed lint errors

### CODE REVIEW

**Review by sandipsk-git — COMMENTED** [review]
This changes working for me .

**Comment by facundoolano** [comment]
Thanks @icarcal !!

**Comment by yashwant-BST** [comment]
When these changes will deploy on the NPM package?

**Comment by xenon92** [comment]
Kindly publish the update on npm.

**Comment by SidiBecker** [comment]
Waiting the update on npm!

**Comment by facundoolano** [comment]
https://github.com/facundoolano/google-play-scraper/issues/496#issuecomment-1006657495

**Pull request merged**
